;;; agent-shell-utils-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list (quote load-path) (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell-context.el

(autoload 'agent-shell-context-emacs-source "agent-shell-context"
"Gather recent Emacs context that has not already been sent.")
(defalias 'agent-shell-context-source #'agent-shell-context-emacs-source)
(autoload 'agent-shell-context-vc-source "agent-shell-context"
"Return the current built-in VC diff as `agent-shell' context, or nil.")
(autoload 'agent-shell-context-magit-source "agent-shell-context"
"Return the current Magit diff section as `agent-shell' context, or nil.")
(defvar agent-shell-context-mode nil
"Non-nil if Agent-Shell-Context mode is enabled.
See the `agent-shell-context-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `agent-shell-context-mode'.")
(custom-autoload 'agent-shell-context-mode "agent-shell-context" nil)
(autoload 'agent-shell-context-mode "agent-shell-context"
"Enable additional context sources for `agent-shell'.

This is a global minor mode.  If called interactively, toggle the
`Agent-Shell-Context mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='agent-shell-context-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-context" '("agent-shell-context-"))


;;; Generated autoloads from agent-shell-dashboard.el

(autoload 'agent-shell-dashboard-refresh "agent-shell-dashboard"
"Refresh live agent-shell, Jira, and PR status incrementally." t)
(autoload 'agent-shell-dashboard-visit "agent-shell-dashboard"
"Visit or launch the agent-shell for the current row." t)
(autoload 'agent-shell-dashboard "agent-shell-dashboard"
"Open the agent-shell worktree dashboard." t)
(register-definition-prefixes "agent-shell-dashboard" '("agent-shell-dashboard-"))


;;; Generated autoloads from agent-shell-fanout.el

(autoload 'agent-shell-fanout-worktrees "agent-shell-fanout"
"Create one worktree-backed `agent-shell' per entry in TASK-SPECS.

TASK-SPECS is an alist of (TITLE . TASK) pairs.  If a TITLE is an absolute
directory path, the final path elements are used as TITLE and the working
directory is that absolute path.  Other specs create or reuse worktrees below
DIRECTORY's Git repository, rename each shell buffer to TITLE, and queue TASK.
When DIRECTORY is nil, use `default-directory'.

(fn TASK-SPECS &optional DIRECTORY SESSION-STRATEGY)" t)
(register-definition-prefixes "agent-shell-fanout" '("agent-shell-fanout-"))


;;; Generated autoloads from agent-shell-jira.el

(autoload 'agent-shell-jira-issues-investigate-marked-with-agent "agent-shell-jira"
"Start worktree-backed agent investigations for marked Jira issues.

If no issues are marked in `*Jira Issues*', emit a message and do nothing.

(fn &optional PROMPT?)" t)
(register-definition-prefixes "agent-shell-jira" '("agent-shell-jira-" "jira-detail--current-key"))


;;; Generated autoloads from agent-shell-nono.el

(autoload 'agent-shell-nono-select-profile "agent-shell-nono"
"Select nono profile NAME for future agent buffers.
Existing agent buffers keep their selected profile.  Use Customize to
persist the default across Emacs restarts.

(fn NAME)" t)
(autoload 'agent-shell-nono-command-prefix "agent-shell-nono"
"Return a nono launch prefix for agent BUFFER, with optional systemd limits.
Local Linux sessions get a private tmpfs /tmp when bubblewrap is available.
Use the buffer's directory as nono's WORKDIR.  Remote processes are left
unwrapped.  Missing nono/profiles are errors when sandboxing is enabled.
Nono validates and enforces the selected JSON policy in either case.

(fn BUFFER)")
(defvar agent-shell-nono-mode nil
"Non-nil if Agent-Shell-Nono mode is enabled.
See the `agent-shell-nono-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `agent-shell-nono-mode'.")
(custom-autoload 'agent-shell-nono-mode "agent-shell-nono" nil)
(autoload 'agent-shell-nono-mode "agent-shell-nono"
"Launch agents with nono and `agent-shell-nono-command-prefix'.

This is a global minor mode.  If called interactively, toggle the
`Agent-Shell-Nono mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='agent-shell-nono-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-nono" '("agent-shell-nono-"))


;;; Generated autoloads from agent-shell-ralph.el

(autoload 'agent-shell-ralph-configure "agent-shell-ralph"
"Configure the continuation rule for the current `agent-shell' buffer." t)
(autoload 'agent-shell-ralph-mode "agent-shell-ralph"
"Keep the current `agent-shell' moving while a local rule matches.

When enabled, the current buffer stores a single continuation rule.  At the end
of each turn, the rule is evaluated.  If it matches the configured trigger,
`agent-shell-prompt-queue' is called with the configured prompt.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Ralph mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-ralph-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'agent-shell-ralph-rate-limit-retry-mode "agent-shell-ralph"
"Retry `agent-shell' requests after transient rate-limit errors.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Ralph-Rate-Limit-Retry mode' mode.  If the prefix argument
is positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-ralph-rate-limit-retry-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-ralph" '("agent-shell-ralph-"))


;;; Generated autoloads from agent-shell-utils.el

(autoload 'agent-shell-utils-unstick "agent-shell-utils"
"Force the current idle `agent-shell' buffer back to prompt-ready state." t)

;;; End of scraped data

(provide 'agent-shell-utils-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-utils-autoloads.el ends here
